apiVersion: v1
kind: Service
metadata:
  name: web-client
spec:
  type: LoadBalancer
  selector:
    web-service: web-client
  ports: 
  - port: 8000
    targetPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-client
spec:
  selector:
    matchLabels:
      web-service: web-client
  template:
    metadata:
      labels:
        web-service: web-client
        system: server
    spec:
      containers:
      - name: tasks
        image: pgyordanovv/agiletracker-client:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: GatewaySettings__BaseAddress
          value: "http://gateway:80"
        - name: AuthorizationServer
          value: "http://gateway-auth:80"
          