apiVersion: v1
kind: Service
metadata:
  name: gateway-auth
spec:
  type: LoadBalancer
  selector:
    web-service: gateway-auth
  ports: 
  - port: 8001
    targetPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-auth
spec:
  selector:
    matchLabels:
      web-service: gateway-auth
  template:
    metadata:
      labels:
        web-service: gateway-auth
        system: server
    spec:
      containers:
      - name: gateway-auth
        image: pgyordanovv/agiletracker-gateway-auth:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: ConnectionStrings__IdentityConnection
          valueFrom:
            secretKeyRef:
              name: environment-secrets
              key: gateway-auth-identity-connection-string
        - name: ConnectionStrings__IdentityServerConnection
          valueFrom:
            secretKeyRef:
              name: environment-secrets
              key: gateway-auth-identity-server-connection-string