apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  type: LoadBalancer
  selector:
    web-service: gateway
  ports: 
  - port: 8001
    targetPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  selector:
    matchLabels:
      web-service: gateway
  template:
    metadata:
      labels:
        web-service: gateway
        system: server
    spec:
      containers:
      - name: tasks
        image: pgyordanovv/agiletracker-gateway:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: AuthorizationServer
          value: "http://gateway-auth:80"
          