apiVersion: v1
kind: Service
metadata:
  name: statistics-database
spec:
  clusterIP: None
  selector:
    database: statistics
  ports: 
  - port: 1433
    targetPort: 1433

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statistics-database
spec:
  selector:
    matchLabels:
      database: statistics
  serviceName: statistics-database
  replicas: 1
  template:
    metadata:
      labels:
        database: statistics
        system: database
    spec:
      terminationGracePeriodSeconds: 60
      securityContext:
        fsGroup: 10001
      containers:
      - name: statistics-database
        image: mcr.microsoft.com/mssql/server:2019-latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 1433
        # resources:
        #   limits:
        #     memory: "500Mi"
        #     cpu: "300m"
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: environment-secrets
              key: statistics-db-password
        volumeMounts:
        - mountPath: "/var/opt/mssql"
          name: statistics-database-pvc
  volumeClaimTemplates:
  - metadata:
      name: statistics-database-pvc
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
      storageClassName: do-block-storage