apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  type: LoadBalancer
  selector:
    eventbus: rabbitmq
  ports: 
  - port: 5672
    name: service-port
    targetPort: 5672
  - port: 15672
    name: admin-port
    targetPort: 15672

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
spec:
  selector:
    matchLabels:
      eventbus: rabbitmq
  serviceName: rabbitmq
  replicas: 1
  template:
    metadata:
      labels:
        eventbus: rabbitmq
        system: eventbus
    spec:
      terminationGracePeriodSeconds: 60
      securityContext:
        fsGroup: 10001
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5672
        - containerPort: 15672
        # resources:
        #   limits:
        #     memory: "500Mi"
        #     cpu: "300m"
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: "guest"
        - name: RABBITMQ_DEFAULT_PASS
          value: "guest"
        volumeMounts:
        - mountPath: "/var/opt/lib/rabbitmq/mnesia"
          name: rabbitmq-pvc
  volumeClaimTemplates:
  - metadata:
      name: rabbitmq-pvc
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
      storageClassName: do-block-storage