apiVersion: v1
kind: Secret
metadata:
  name: environment-secrets
data:
  identity-db-password: U3RyMG5nUGFzc3dvcmQxIQ==
  tasks-db-password: U3RyMG5nUGFzc3dvcmQxIQ==
  statistics-db-password: U3RyMG5nUGFzc3dvcmQxIQ==